/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TicTacToeGUI;

/**
 *
 * @author Patrick
 */
public class TicTacToeGUI extends javax.swing.JFrame {
    
    private Board board;
    private RobotPlayer Robot;
    private HumanPlayer You;
    

    /**
     * Creates new form TicTacToeGUI
     */
    public TicTacToeGUI() {
        initComponents();
        board = new Board();
        Robot = new RobotPlayer(board, "Computer");
        You = new HumanPlayer(board, "You");
        Robot.setLetter("X");
        You.setLetter("O");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonR0C0 = new javax.swing.JButton();
        buttonR0C1 = new javax.swing.JButton();
        buttonR0C2 = new javax.swing.JButton();
        buttonR1C0 = new javax.swing.JButton();
        buttonR1C1 = new javax.swing.JButton();
        buttonR1C2 = new javax.swing.JButton();
        buttonR2C0 = new javax.swing.JButton();
        buttonR2C1 = new javax.swing.JButton();
        buttonR2C2 = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe");

        buttonR0C0.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        buttonR0C0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonR0C0ActionPerformed(evt);
            }
        });

        buttonR0C1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        buttonR0C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonR0C1ActionPerformed(evt);
            }
        });

        buttonR0C2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        buttonR0C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonR0C2ActionPerformed(evt);
            }
        });

        buttonR1C0.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        buttonR1C0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonR1C0ActionPerformed(evt);
            }
        });

        buttonR1C1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        buttonR1C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonR1C1ActionPerformed(evt);
            }
        });

        buttonR1C2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        buttonR1C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonR1C2ActionPerformed(evt);
            }
        });

        buttonR2C0.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        buttonR2C0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonR2C0ActionPerformed(evt);
            }
        });

        buttonR2C1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        buttonR2C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonR2C1ActionPerformed(evt);
            }
        });

        buttonR2C2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        buttonR2C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonR2C2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonR0C0, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonR0C1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonR0C2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonR1C0, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonR1C1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonR1C2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonR2C0, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonR2C1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonR2C2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(resultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonR0C0, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonR0C1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonR0C2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonR1C1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonR1C0, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonR1C2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonR2C1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonR2C0, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonR2C2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultLabel)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonR0C0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonR0C0ActionPerformed
        // TODO add your handling code here:
        if (board.checkWinner())
            return;
        if (You.select(0,0)) {
            buttonR0C0.setText(You.getLetter());
            Robot.select();
            robotPick(Robot.getRow(),Robot.getColumn());
            System.out.println(board);
            finishGame();
        }
        else
            return;
    }//GEN-LAST:event_buttonR0C0ActionPerformed

    private void buttonR0C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonR0C2ActionPerformed
        // TODO add your handling code here:
        if (board.checkWinner())
            return;
        if (You.select(0,2)) {
            buttonR0C2.setText(You.getLetter());
            Robot.select();
            robotPick(Robot.getRow(),Robot.getColumn());
            System.out.println(board);
            finishGame();
        }
        else
            return;
    }//GEN-LAST:event_buttonR0C2ActionPerformed

    private void buttonR1C0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonR1C0ActionPerformed
        // TODO add your handling code here:
        if (board.checkWinner())
            return;
        if (You.select(1,0)) {
            buttonR1C0.setText(You.getLetter());
            Robot.select();
            robotPick(Robot.getRow(),Robot.getColumn());
            System.out.println(board);
            finishGame();
        }
        else
            return;
    }//GEN-LAST:event_buttonR1C0ActionPerformed

    private void buttonR1C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonR1C1ActionPerformed
        // TODO add your handling code here:
        if (board.checkWinner())
            return;
        if (You.select(1,1)) {
            buttonR1C1.setText(You.getLetter());
            Robot.select();
            robotPick(Robot.getRow(),Robot.getColumn());
            System.out.println(board);
            finishGame();
        }
        else
            return;
    }//GEN-LAST:event_buttonR1C1ActionPerformed

    private void buttonR0C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonR0C1ActionPerformed
        // TODO add your handling code here:
        if (board.checkWinner())
            return;
        if (You.select(0,1)) {
            buttonR0C1.setText(You.getLetter());
            Robot.select();
            robotPick(Robot.getRow(),Robot.getColumn());
            System.out.println(board);
            finishGame();
        }
        else
            return;
    }//GEN-LAST:event_buttonR0C1ActionPerformed

    private void buttonR1C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonR1C2ActionPerformed
        // TODO add your handling code here:
        if (board.checkWinner())
            return;
        if (You.select(1,2)) {
            buttonR1C2.setText(You.getLetter());
            Robot.select();
            robotPick(Robot.getRow(),Robot.getColumn());
            System.out.println(board);
            finishGame();
        }
        else
            return;
    }//GEN-LAST:event_buttonR1C2ActionPerformed

    private void buttonR2C0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonR2C0ActionPerformed
        // TODO add your handling code here:
        if (board.checkWinner())
            return;
        if (You.select(2,0)) {
            buttonR2C0.setText(You.getLetter());
            Robot.select();
            robotPick(Robot.getRow(),Robot.getColumn());
            System.out.println(board);
            finishGame();
        }
        else
            return;
    }//GEN-LAST:event_buttonR2C0ActionPerformed

    private void buttonR2C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonR2C1ActionPerformed
        // TODO add your handling code here:
        if (board.checkWinner())
            return;
        if (You.select(2,1)) {
            buttonR2C1.setText(You.getLetter());
            Robot.select();
            robotPick(Robot.getRow(),Robot.getColumn());
            System.out.println(board);
            finishGame();
        }
        else
            return;
    }//GEN-LAST:event_buttonR2C1ActionPerformed

    private void buttonR2C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonR2C2ActionPerformed
        // TODO add your handling code here:
        if (board.checkWinner())
            return;
        if (You.select(2,2)) {
            buttonR2C2.setText(You.getLetter());
            Robot.select();
            robotPick(Robot.getRow(),Robot.getColumn());
            System.out.println(board);
            finishGame();
        }
        else
            return;
    }//GEN-LAST:event_buttonR2C2ActionPerformed
    
    /**
     * Method that changes the text of the button the robot has selected
     * Does nothing if player has already won
     * @param r row that robot selected
     * @param c column that robot selected
     */
    private void robotPick(int r, int c){
        if (You.sameLetter(board.getWinnerLetter()) || board.checkTie())
            return;
        if (r == 0){
            if (c == 0)
                buttonR0C0.setText(Robot.getLetter());
            else if (c == 1)
                buttonR0C1.setText(Robot.getLetter());
            else if (c == 2)
                buttonR0C2.setText(Robot.getLetter());
        }
        else if (r == 1){
            if (c == 0)
                buttonR1C0.setText(Robot.getLetter());
            else if (c == 1)
                buttonR1C1.setText(Robot.getLetter());
            else if (c == 2)
                buttonR1C2.setText(Robot.getLetter());
            }
        else if (r == 2){
            if (c == 0)
                buttonR2C0.setText(Robot.getLetter());
            else if (c == 1)
                buttonR2C1.setText(Robot.getLetter());
            else if (c == 2)
                buttonR2C2.setText(Robot.getLetter());
            }

    }
    
    /**
     * Method that firsts checks if there is a winner or tie, 
     * then checks who won, 
     * then changes resultLabel to result
     */
    private void finishGame(){
        if (board.checkWinner()){
            if (board.checkTie() && !(board.checkDiagonal() || board.checkRows() || board.checkCol()))
                resultLabel.setText("There is a tie!");
            else {
                String winnerLetter = board.getWinnerLetter();
                if (Robot.sameLetter(winnerLetter))
                    resultLabel.setText("Robot wins!");
                else if (You.sameLetter(winnerLetter))
                    resultLabel.setText("You win!");
            }   
        } 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonR0C0;
    private javax.swing.JButton buttonR0C1;
    private javax.swing.JButton buttonR0C2;
    private javax.swing.JButton buttonR1C0;
    private javax.swing.JButton buttonR1C1;
    private javax.swing.JButton buttonR1C2;
    private javax.swing.JButton buttonR2C0;
    private javax.swing.JButton buttonR2C1;
    private javax.swing.JButton buttonR2C2;
    private javax.swing.JLabel resultLabel;
    // End of variables declaration//GEN-END:variables
}
